version: '3.9'

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/node_app/app
    command: /bin/sh -c "chmod +x entrypoint.sh && /node_app/app/entrypoint.sh"
    env_file:
      - .env